name: Build Watermark App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build binary
      run: |
        pyinstaller --onefile kpu_watermark.py

    - name: Build DMG (macOS only)
      if: matrix.os == 'macos-latest'
      run: |
        brew install create-dmg
        create-dmg \
          --volname "KPU Watermark" \
          --window-size 600 400 \
          --app-drop-link 400 200 \
          KPU_Watermark.dmg \
          dist/kpu_watermark.app

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: watermark-${{ matrix.os }}
        path: |
          dist/*
          *.dmg
